package com.yamone.korean.learning

data class BasicSentenceLesson(
    val id: String,
    val pattern: String,
    val korean: String,
    val correctChunks: List<String>,
    val choiceChunks: List<String>,
    val translations: Map<String, String>,
    val grammarNotes: Map<String, String>,
) {
    fun meaning(languageCode: String?): String =
        translations[languageCode] ?: translations.getValue("en")

    fun grammarNote(languageCode: String?): String =
        grammarNotes[languageCode] ?: grammarNotes.getValue("en")
}

object BasicSentenceCatalog {
    val lessons: List<BasicSentenceLesson> = listOf(
        BasicSentenceLesson(
            id = "sentence_identity",
            pattern = "저는 ___이에요/예요",
            korean = "저는 학생이에요.",
            correctChunks = listOf("저는", "학생이에요"),
            choiceChunks = listOf("학생이에요", "저는"),
            translations = translations(
                "I am a student.",
                "Soy estudiante.",
                "Je suis étudiant(e).",
                "Tôi là học sinh / sinh viên.",
                "ฉัน/ผมเป็นนักเรียน",
                "Saya seorang pelajar.",
            ),
            grammarNotes = translations(
                "저는 sets 'I' as the topic. 이에요/예요 politely means 'am/is/are'.",
                "저는 marca 'yo' como tema. 이에요/예요 es una forma cortés de 'ser'.",
                "저는 marque « je » comme thème. 이에요/예요 correspond poliment à « être ».",
                "저는 đặt 'tôi' làm chủ đề. 이에요/예요 là cách nói lịch sự của 'là'.",
                "저는 ทำให้ 'ฉัน/ผม' เป็นหัวข้อ และ 이에요/예요 ใช้บอกว่า 'เป็น' แบบสุภาพ",
                "저는 menandai 'saya' sebagai topik. 이에요/예요 berarti 'adalah' secara sopan.",
            ),
        ),
        BasicSentenceLesson(
            id = "sentence_like",
            pattern = "저는 ___을/를 좋아해요",
            korean = "저는 커피를 좋아해요.",
            correctChunks = listOf("저는", "커피를", "좋아해요"),
            choiceChunks = listOf("좋아해요", "저는", "커피를"),
            translations = translations(
                "I like coffee.",
                "Me gusta el café.",
                "J'aime le café.",
                "Tôi thích cà phê.",
                "ฉัน/ผมชอบกาแฟ",
                "Saya suka kopi.",
            ),
            grammarNotes = translations(
                "을/를 marks what you like. Korean normally places the action at the end.",
                "을/를 marca aquello que te gusta. En coreano, la acción suele ir al final.",
                "을/를 marque ce que l'on aime. En coréen, l'action se place généralement à la fin.",
                "을/를 đánh dấu đối tượng bạn thích. Trong tiếng Hàn, động từ thường đứng cuối câu.",
                "을/를 ใช้ชี้สิ่งที่ชอบ และภาษาเกาหลีมักวางคำกริยาไว้ท้ายประโยค",
                "을/를 menandai objek yang disukai. Dalam bahasa Korea, kata kerja biasanya berada di akhir.",
            ),
        ),
        BasicSentenceLesson(
            id = "sentence_go_school",
            pattern = "[시간] [장소]에 가요",
            korean = "오늘 학교에 가요.",
            correctChunks = listOf("오늘", "학교에", "가요"),
            choiceChunks = listOf("학교에", "가요", "오늘"),
            translations = translations(
                "I go to school today.",
                "Hoy voy a la escuela.",
                "Aujourd'hui, je vais à l'école.",
                "Hôm nay tôi đi học.",
                "วันนี้ฉัน/ผมไปโรงเรียน",
                "Hari ini saya pergi ke sekolah.",
            ),
            grammarNotes = translations(
                "에 marks the destination. A common order is time → place → action.",
                "에 marca el destino. Un orden común es tiempo → lugar → acción.",
                "에 marque la destination. Un ordre courant est temps → lieu → action.",
                "에 đánh dấu điểm đến. Thứ tự thường gặp là thời gian → nơi chốn → hành động.",
                "에 ใช้บอกจุดหมาย ลำดับที่พบบ่อยคือ เวลา → สถานที่ → การกระทำ",
                "에 menandai tujuan. Urutan umum adalah waktu → tempat → tindakan.",
            ),
        ),
        BasicSentenceLesson(
            id = "sentence_eat_now",
            pattern = "[시간] [대상]을/를 [동작]",
            korean = "지금 밥을 먹어요.",
            correctChunks = listOf("지금", "밥을", "먹어요"),
            choiceChunks = listOf("먹어요", "지금", "밥을"),
            translations = translations(
                "I am eating now.",
                "Estoy comiendo ahora.",
                "Je mange maintenant.",
                "Bây giờ tôi đang ăn.",
                "ตอนนี้ฉัน/ผมกำลังกินข้าว",
                "Saya sedang makan sekarang.",
            ),
            grammarNotes = translations(
                "The subject can be omitted when it is obvious. 밥을 is the object, and 먹어요 comes last.",
                "El sujeto puede omitirse si es obvio. 밥을 es el objeto y 먹어요 va al final.",
                "Le sujet peut être omis s'il est évident. 밥을 est l'objet et 먹어요 vient à la fin.",
                "Có thể lược chủ ngữ khi đã rõ. 밥을 là tân ngữ và 먹어요 đứng cuối.",
                "ละประธานได้เมื่อเข้าใจว่าเป็นใคร 밥을 คือกรรม และ 먹어요 อยู่ท้ายประโยค",
                "Subjek dapat dihilangkan jika sudah jelas. 밥을 adalah objek dan 먹어요 berada di akhir.",
            ),
        ),
        BasicSentenceLesson(
            id = "sentence_go_work",
            pattern = "[시간] [장소]에 가요",
            korean = "내일 회사에 가요.",
            correctChunks = listOf("내일", "회사에", "가요"),
            choiceChunks = listOf("가요", "내일", "회사에"),
            translations = translations(
                "I go to work tomorrow.",
                "Mañana voy al trabajo.",
                "Demain, je vais au travail.",
                "Ngày mai tôi đi làm.",
                "พรุ่งนี้ฉัน/ผมไปทำงาน",
                "Besok saya pergi bekerja.",
            ),
            grammarNotes = translations(
                "Change only the time or place to make many useful sentences with the same pattern.",
                "Cambia solo el tiempo o el lugar para crear muchas frases útiles con el mismo patrón.",
                "Change simplement le moment ou le lieu pour créer de nombreuses phrases utiles avec le même modèle.",
                "Chỉ cần đổi thời gian hoặc địa điểm là bạn có thể tạo nhiều câu hữu ích theo cùng mẫu.",
                "เปลี่ยนเพียงเวลาหรือสถานที่ ก็สร้างประโยคที่ใช้ได้จริงอีกมากด้วยรูปแบบเดิม",
                "Cukup ganti waktu atau tempat untuk membuat banyak kalimat berguna dengan pola yang sama.",
            ),
        ),
        BasicSentenceLesson(
            id = "sentence_friend_comes",
            pattern = "[주어]이/가 [장소]에 와요",
            korean = "친구가 집에 와요.",
            correctChunks = listOf("친구가", "집에", "와요"),
            choiceChunks = listOf("집에", "와요", "친구가"),
            translations = translations(
                "A friend comes to my home.",
                "Un amigo viene a mi casa.",
                "Un ami vient chez moi.",
                "Một người bạn đến nhà tôi.",
                "เพื่อนมาที่บ้าน",
                "Seorang teman datang ke rumah saya.",
            ),
            grammarNotes = translations(
                "이/가 marks the subject. 에 marks the destination, and 와요 ('comes') finishes the sentence.",
                "이/가 marca el sujeto. 에 marca el destino y 와요 ('viene') termina la oración.",
                "이/가 marque le sujet. 에 marque la destination et 와요 (« vient ») termine la phrase.",
                "이/가 đánh dấu chủ ngữ. 에 đánh dấu điểm đến và 와요 ('đến') đứng cuối câu.",
                "이/가 ใช้ชี้ประธาน 에 ใช้ชี้จุดหมาย และ 와요 ('มา') อยู่ท้ายประโยค",
                "이/가 menandai subjek. 에 menandai tujuan dan 와요 ('datang') berada di akhir kalimat.",
            ),
        ),
        BasicSentenceLesson(
            id = "sentence_name_question",
            pattern = "[명사]이/가 뭐예요?",
            korean = "이름이 뭐예요?",
            correctChunks = listOf("이름이", "뭐예요"),
            choiceChunks = listOf("뭐예요", "이름이"),
            translations = translations(
                "What's your name?",
                "¿Cómo te llamas?",
                "Comment tu t'appelles ?",
                "Bạn tên là gì?",
                "ชื่ออะไร?",
                "Siapa nama Anda?",
            ),
            grammarNotes = translations(
                "이/가 marks the thing being asked about. 뭐예요? politely asks 'what is it?'.",
                "이/가 marca aquello sobre lo que se pregunta. 뭐예요? pregunta cortésmente «¿qué es?».",
                "이/가 marque ce dont on parle. 뭐예요? demande poliment « qu'est-ce que c'est ? ».",
                "이/가 đánh dấu điều đang được hỏi. 뭐예요? là cách hỏi lịch sự 'là gì?'.",
                "이/가 ใช้ชี้สิ่งที่กำลังถาม และ 뭐예요? ใช้ถามอย่างสุภาพว่า 'คืออะไร?'",
                "이/가 menandai hal yang ditanyakan. 뭐예요? adalah cara sopan untuk bertanya 'apa?'.",
            ),
        ),
        BasicSentenceLesson(
            id = "sentence_order_one",
            pattern = "[메뉴] 하나 주세요",
            korean = "비빔밥 하나 주세요.",
            correctChunks = listOf("비빔밥", "하나", "주세요"),
            choiceChunks = listOf("주세요", "비빔밥", "하나"),
            translations = translations(
                "One bibimbap, please.",
                "Un bibimbap, por favor.",
                "Un bibimbap, s'il vous plaît.",
                "Cho tôi một bibimbap.",
                "ขอบิบิมบับหนึ่งที่ค่ะ/ครับ",
                "Satu bibimbap, tolong.",
            ),
            grammarNotes = translations(
                "하나 means 'one'. 주세요 politely asks someone to give or serve something.",
                "하나 significa 'uno'. 주세요 se usa para pedir algo de forma cortés.",
                "하나 signifie « un ». 주세요 permet de demander quelque chose poliment.",
                "하나 nghĩa là 'một'. 주세요 dùng để yêu cầu hoặc gọi món một cách lịch sự.",
                "하나 แปลว่า 'หนึ่ง' และ 주세요 ใช้ขอสิ่งของหรือสั่งอาหารอย่างสุภาพ",
                "하나 berarti 'satu'. 주세요 dipakai untuk meminta sesuatu dengan sopan.",
            ),
        ),
        BasicSentenceLesson(
            id = "sentence_price_question",
            pattern = "이거 얼마예요?",
            korean = "이거 얼마예요?",
            correctChunks = listOf("이거", "얼마예요"),
            choiceChunks = listOf("얼마예요", "이거"),
            translations = translations(
                "How much is this?",
                "¿Cuánto cuesta esto?",
                "Combien coûte ceci ?",
                "Cái này bao nhiêu tiền?",
                "อันนี้เท่าไหร่?",
                "Berapa harga ini?",
            ),
            grammarNotes = translations(
                "이거 means 'this'. 얼마예요? is the everyday polite way to ask a price.",
                "이거 significa 'esto'. 얼마예요? es una forma cotidiana y cortés de preguntar el precio.",
                "이거 signifie « ceci ». 얼마예요? est la façon polie et courante de demander le prix.",
                "이거 nghĩa là 'cái này'. 얼마예요? là cách hỏi giá lịch sự và thông dụng.",
                "이거 แปลว่า 'อันนี้' และ 얼마예요? เป็นวิธีถามราคาแบบสุภาพที่ใช้บ่อย",
                "이거 berarti 'ini'. 얼마예요? adalah cara sopan sehari-hari untuk menanyakan harga.",
            ),
        ),
        BasicSentenceLesson(
            id = "sentence_restroom_where",
            pattern = "[장소]이/가 어디예요?",
            korean = "화장실이 어디예요?",
            correctChunks = listOf("화장실이", "어디예요"),
            choiceChunks = listOf("어디예요", "화장실이"),
            translations = translations(
                "Where is the restroom?",
                "¿Dónde está el baño?",
                "Où sont les toilettes ?",
                "Nhà vệ sinh ở đâu?",
                "ห้องน้ำอยู่ที่ไหน?",
                "Di mana toiletnya?",
            ),
            grammarNotes = translations(
                "어디 means 'where'. Put the place before 어디예요? to ask where it is.",
                "어디 significa 'dónde'. Pon el lugar antes de 어디예요? para preguntar dónde está.",
                "어디 signifie « où ». Place le lieu avant 어디예요? pour demander où il se trouve.",
                "어디 nghĩa là 'ở đâu'. Đặt địa điểm trước 어디예요? để hỏi vị trí.",
                "어디 แปลว่า 'ที่ไหน' วางสถานที่ไว้หน้า 어디예요? เพื่อถามว่าอยู่ที่ไหน",
                "어디 berarti 'di mana'. Letakkan tempat sebelum 어디예요? untuk menanyakan lokasinya.",
            ),
        ),
        BasicSentenceLesson(
            id = "sentence_how_to_station",
            pattern = "[장소]에 어떻게 가요?",
            korean = "서울역에 어떻게 가요?",
            correctChunks = listOf("서울역에", "어떻게", "가요"),
            choiceChunks = listOf("가요", "어떻게", "서울역에"),
            translations = translations(
                "How do I get to Seoul Station?",
                "¿Cómo llego a la estación de Seúl?",
                "Comment aller à la gare de Séoul ?",
                "Đi đến ga Seoul như thế nào?",
                "ไปสถานีโซลอย่างไร?",
                "Bagaimana cara pergi ke Stasiun Seoul?",
            ),
            grammarNotes = translations(
                "에 marks the destination. 어떻게 means 'how', and the action 가요 comes at the end.",
                "에 marca el destino. 어떻게 significa 'cómo' y la acción 가요 va al final.",
                "에 marque la destination. 어떻게 signifie « comment » et 가요 se place à la fin.",
                "에 đánh dấu điểm đến. 어떻게 nghĩa là 'như thế nào' và 가요 đứng cuối câu.",
                "에 ใช้บอกจุดหมาย 어떻게 แปลว่า 'อย่างไร' และ 가요 อยู่ท้ายประโยค",
                "에 menandai tujuan. 어떻게 berarti 'bagaimana', dan 가요 berada di akhir.",
            ),
        ),
        BasicSentenceLesson(
            id = "sentence_head_hurts",
            pattern = "[몸]이/가 아파요",
            korean = "머리가 아파요.",
            correctChunks = listOf("머리가", "아파요"),
            choiceChunks = listOf("아파요", "머리가"),
            translations = translations(
                "My head hurts.",
                "Me duele la cabeza.",
                "J'ai mal à la tête.",
                "Tôi đau đầu.",
                "ปวดหัวค่ะ/ครับ",
                "Kepala saya sakit.",
            ),
            grammarNotes = translations(
                "Use [body part] + 이/가 아파요 to say where you hurt. Korean often omits 'my' when the meaning is obvious.",
                "Usa [parte del cuerpo] + 이/가 아파요 para decir dónde te duele. En coreano suele omitirse 'mi' si es obvio.",
                "Utilise [partie du corps] + 이/가 아파요 pour dire où tu as mal. Le coréen omet souvent « mon/ma » quand c'est évident.",
                "Dùng [bộ phận cơ thể] + 이/가 아파요 để nói chỗ bị đau. Tiếng Hàn thường lược 'của tôi' khi đã rõ.",
                "ใช้ [ส่วนของร่างกาย] + 이/가 아파요 เพื่อบอกว่าเจ็บตรงไหน ภาษาเกาหลีมักละคำว่า 'ของฉัน' เมื่อเข้าใจได้",
                "Gunakan [bagian tubuh] + 이/가 아파요 untuk mengatakan bagian yang sakit. Bahasa Korea sering menghilangkan kata 'saya' bila sudah jelas.",
            ),
        ),
        BasicSentenceLesson(
            id = "sentence_repeat_please",
            pattern = "다시 [동작]해 주세요",
            korean = "다시 말해 주세요.",
            correctChunks = listOf("다시", "말해", "주세요"),
            choiceChunks = listOf("주세요", "다시", "말해"),
            translations = translations(
                "Please say that again.",
                "Repítalo, por favor.",
                "Répétez, s'il vous plaît.",
                "Vui lòng nói lại.",
                "พูดอีกครั้งได้ไหมคะ/ครับ",
                "Tolong katakan lagi.",
            ),
            grammarNotes = translations(
                "다시 means 'again'. -아/어 주세요 makes a polite request: 'please do ...'.",
                "다시 significa 'otra vez'. -아/어 주세요 convierte la acción en una petición cortés: «por favor, ...».",
                "다시 signifie « encore ». -아/어 주세요 transforme l'action en demande polie : « s'il vous plaît, ... ».",
                "다시 nghĩa là 'lại'. -아/어 주세요 tạo lời yêu cầu lịch sự: 'vui lòng hãy...'.",
                "다시 แปลว่า 'อีกครั้ง' และ -아/어 주세요 ใช้ขอร้องอย่างสุภาพว่า 'กรุณา...' ",
                "다시 berarti 'lagi'. -아/어 주세요 membuat permintaan sopan: 'tolong ...'.",
            ),
        ),
        BasicSentenceLesson(
            id = "sentence_meet_time",
            pattern = "몇 시에 [동작]할까요?",
            korean = "몇 시에 만날까요?",
            correctChunks = listOf("몇 시에", "만날까요"),
            choiceChunks = listOf("만날까요", "몇 시에"),
            translations = translations(
                "What time shall we meet?",
                "¿A qué hora nos vemos?",
                "À quelle heure on se retrouve ?",
                "Mấy giờ chúng ta gặp nhau?",
                "เจอกันกี่โมงดี?",
                "Kita bertemu jam berapa?",
            ),
            grammarNotes = translations(
                "몇 시에 asks 'at what time'. -ㄹ/을까요? is a polite way to suggest or decide something together.",
                "몇 시에 pregunta 'a qué hora'. -ㄹ/을까요? se usa cortésmente para proponer o decidir algo juntos.",
                "몇 시에 signifie « à quelle heure ». -ㄹ/을까요? sert à proposer ou décider quelque chose ensemble poliment.",
                "몇 시에 nghĩa là 'mấy giờ'. -ㄹ/을까요? dùng để đề nghị hoặc cùng nhau quyết định một cách lịch sự.",
                "몇 시에 แปลว่า 'กี่โมง' และ -ㄹ/을까요? ใช้ชวนหรือเสนอเพื่อตัดสินใจร่วมกันอย่างสุภาพ",
                "몇 시에 berarti 'jam berapa'. -ㄹ/을까요? dipakai untuk mengajak atau memutuskan sesuatu bersama dengan sopan.",
            ),
        )
    )
}

private fun translations(
    en: String,
    es: String,
    fr: String,
    vi: String,
    th: String,
    id: String,
): Map<String, String> = mapOf(
    "en" to en,
    "es" to es,
    "fr" to fr,
    "vi" to vi,
    "th" to th,
    "id" to id,
)
